### ISSUE TITLE
Implementation needed

### ISSUE THREAD

**Issue by ianpartridge** [IBM-Swift/Kitura-Request#1]
@michalkalinowski- Can you open a PR against this repo with your implementation?  Thank you!

**Comment by michalkalinowski-** [comment]
Sure, let me update license first. I'm currently on holidays till the end of the week so I may be a bit slow to reply

**Comment by ianpartridge** [comment]
Great. Thank you 😃

**Comment by ianpartridge** [comment]
Hi @michalkalinowski- any news on this?

**Comment by ianpartridge** [comment]
Hi @michalkalinowski- are you still able to help with this?

**Comment by michalkalinowski-** [comment]
Sorry @ianpartridge i was offline for the most part of the last month. I'm preparing a PR, just need to migrate my code to `DEVELOPMENT-SNAPSHOT-2016-06-20-a`

**Comment by ianpartridge** [comment]
Great - looking forward to it.

**Comment by michalkalinowski-** [comment]
Hello, here's my fork: https://github.com/michalkalinowski-/Kitura-Request/tree/repo_merge

Unfortunately I can not open PR just like that as my changes rewrite history of this repo so they need to be force applied. Any idea how to proceed?

**Comment by ianpartridge** [comment]
Hmm, is it essential to keep your commit history so far?

**Comment by shmuelk** [comment]
I agree, why not just create a new fork of the Kitura-Request repo and copy your files....

**Comment by ianpartridge** [comment]
@michalkalinowski- we'd still love to receive a PR for this... :)
