### ISSUE TITLE
I cannot get Package Manager to pull this repo

### ISSUE THREAD

**Issue by vherrin** [IBM-Swift/Kitura-Request#10]
I've updated git with no success

error: no such remote ref f15b3cc4de0345999098153584ebc89cb64240b0
Fetched in submodule path 'Package-Builder', but it did not contain f15b3cc4de0345999098153584ebc89cb64240b0. Direct fetching of that commit failed.

error: Failed to clone https://github.com/IBM-Swift/Kitura-Request.git to /Users/user/Github/swift-watson-sdk/Packages/Kitura-Request.git

**Comment by rob-deans** [comment]
Hi, I have managed to clone Kitura-Request, did you just run `git clone https://github.com/IBM-Swift/Kitura-Request.git`?

**Comment by vherrin** [comment]
Here is more context.  I added the line - .Package(url: "https://github.com/IBM-Swift/Kitura-Request.git", majorVersion: 0) to my Package.swift file to this repo - https://github.com/IBM-Swift/swift-watson-sdk

Here is the output error 

Cloning into '/Users/vincentherrin/Github/swift-watson-sdk/Packages/Kitura-Request.git/Package-Builder'...
error: no such remote ref f15b3cc4de0345999098153584ebc89cb64240b0
Fetched in submodule path 'Package-Builder', but it did not contain f15b3cc4de0345999098153584ebc89cb64240b0. Direct fetching of that commit failed.

After talking to the Swift@IBM team, it may be the commit of the Package-Builder submodule needs updating.

**Comment by rob-deans** [comment]
Hi @vherrin please let me know if the latest change has fixed it

**Comment by vherrin** [comment]
It is retrieving correctly now.  

Awesome thanks!
