### ISSUE TITLE
DELETE method not working?

### ISSUE THREAD

**Issue by cbarrerah-sogeti** [IBM-Swift/Kitura-Request#30]
Hi,

First of all: i know this is a WIP module and i'm not complaining :)

I've been using Kitura-Request to enable some http calls from my swift server app, and i've managed to use GET and POST without troubles authenticating through tokens in the parameters of the HTTP call to Trello.

But when i tried to use the DELETE method (.delete), i'm getting an 401 unauthorized response every time. My first thought was that i had the wrong permissions or token, so i tried the same HTTP call with the same parameters through Postman, and it worked as expected.

I tried sniffing the http calls through httpry but they all come without the HTTP method nor the full call.

Is it possible to add a method to the Kitura-Request class that simply outputs the exact http call that the request is executing, so it's easier to debug?

And is it possible that Kitura-Request is not handling the parameters in the same way when using the .delete method?

Thanks in advance.

By the way, great work with this module, the only one that i found that works for HTTP calls in swift for linux ;)

**Comment by cbarrerah-sogeti** [comment]
I performed additional debugging by using httpbin.org and verified that the DELETE method ignores the parameters defined for a request -> http://httpbin.org/delete?token="My wonderfull Token"&key="My wonderfull key"
Response from Postman:
{
    "args": {
        "key": "\"My wonderfull key\"",
        "token": "\"My wonderfull Token\""
    },
    "data": "",
    "files": {},
    "form": {},
    "headers": {
        "Accept": "*/*",
        "Accept-Encoding": "gzip, deflate",
        "Cache-Control": "no-cache",
        "Connection": "close",
        "Content-Length": "0",
        "Host": "httpbin.org",
        "Postman-Token": "d72bd1d1-c087-4887-91c7-f7514f3e4d23",
        "User-Agent": "PostmanRuntime/6.1.6",
        "X-Bluecoat-Via": "6096663e10784807"
    },
    "json": null,
    "origin": "15.90.162.11",
    "url": "http://httpbin.org/delete?token=\"My wonderfull Token\"&key=\"My wonderfull key\""
}

The same output when invoked from Kitura-Request:
we use this URL: http://httpbin.org/delete
We provide the following params: ["token": "My wonderfull token", "key": "My wonderfull key"]

{
  "args": {},
  "data": "",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "*/*",
    "Connection": "close",
    "Content-Length": "0",
    "Content-Type": "application/x-www-form-urlencoded; charset=utf-8",
    "Host": "httpbin.org",
    "X-Bluecoat-Via": "7039f9d976f8af11"
  },
  "json": null,
  "origin": "15.195.185.83",
  "url": "http://httpbin.org/delete"
}

The parameters are not included in the HTTP call.

**Comment by cbarrerah-sogeti** [comment]
When trying with the same parameters for the POST method, Kitura-Request includes them in the form section:
we use this URL: http://httpbin.org/post
We provide the following params: ["token": "My wonderfull token", "key": "My wonderfull key"]

{
  "args": {},
  "data": "",
  "files": {},
  "form": {
    "key": "My wonderfull key",
    "token": "My wonderfull token"
  },
  "headers": {
    "Accept": "*/*",
    "Connection": "close",
    "Content-Length": "47",
    "Content-Type": "application/x-www-form-urlencoded; charset=utf-8",
    "Host": "httpbin.org",
    "X-Bluecoat-Via": "7039f9d976f8af11"
  },
  "json": null,
  "origin": "-",
  "url": "http://httpbin.org/post"
}

**Comment by cbarrerah-sogeti** [comment]
Found a Fix:

The Sources/KituraRequest/Encoding/URLEncoding.swift file needs to include the "DELETE" method in the list of the ones that encode the parameters in the query. I forked, tested the fix and it works as expected ^.^

I'll try to put a PR with the fix later.

**Comment by kweinmeister** [comment]
PR merged. Thanks!
