### ISSUE TITLE
Tag is missing and also wrong Kitura-net dependencies

### ISSUE THREAD

**Issue by JacopoMangiavacchi** [IBM-Swift/Kitura-Request#8]
Compile error: No version tag found in (...) package. Add a version tag with "git tag" command. Example: "git tag 0.1.0"

Also I think Kitura-net dependencies in Package.swift should have majorVersion 1

.Package(url: "https://github.com/IBM-Swift/Kitura-net.git", majorVersion: 1)

**Comment by rob-deans** [comment]
Will fix, but in the future there will be no dependency on Kitura-net
